### PR TITLE
Add translation

### PR DESCRIPTION
**Pull request by daybreak1929**
Add Simplified Chinese（简体中文） and Traditional Chinese（繁體中文） Translation

### CODE REVIEW

**Comment by kralinc** [comment]
Is the translation for "mustMatchKingdom Description" accurate? A machine translation on deepl.com for "发生叛乱的城市是否要敌对原国家?" is "Are cities in rebellion to be hostile to the original state?". The feature has nothing to do with whether the rebellion starts at war or not, just whether the culture of the rebelling city has to be the same as the culture of the country it's rebelling against.

**Comment by daybreak1929** [comment]
> Is the translation for "mustMatchKingdom Description" accurate? A machine translation on deepl.com for "发生叛乱的城市是否要敌对原国家?" is "Are cities in rebellion to be hostile to the original state?". The feature has nothing to do with whether the rebellion starts at war or not, just whether the culture of the rebelling city has to be the same as the culture of the country it's rebelling against.

sorry. I misunderstood. XD

**Comment by kralinc** [comment]
Hi sorry, I'm still not sure the new translation is correct. The machine translation of "开启后叛乱的城市仍然会归属于原王国的文明" is "After turning on, the rebellious cities will still belong to the civilization of the original kingdom.", which is not what the feature does. Here's what it does:

* For example, the kingdom has Culture A. The city that is going to rebel has Culture B.
* If mustMatchKingdom is ON, then the city cannot produce a new culture, because Culture B (city culture) does not match Culture A (kingdom culture)
* If mustMatchKingdom is OFF, then the city can produce a new culture, because the culture of the city does not need to match the culture of the kingdom.

I tried google translate and it came up with "如果启用，叛乱城市的文化必须与其来源王国的文化相匹配。" 

I don't mean to nitpick, I just want to be sure the translation is right. Let me know if you have any questions.

**Comment by daybreak1929** [comment]
There is no problem ：） . my translation is partial to the spoken language and the vanilla Chinese translation

**Comment by daybreak1929** [comment]
> Hi sorry, I'm still not sure the new translation is correct. The machine translation of "开启后叛乱的城市仍然会归属于原王国的文明" is "After turning on, the rebellious cities will still belong to the civilization of the original kingdom.", which is not what the feature does. Here's what it does:
> 
> * For example, the kingdom has Culture A. The city that is going to rebel has Culture B.
> * If mustMatchKingdom is ON, then the city cannot produce a new culture, because Culture B (city culture) does not match Culture A (kingdom culture)
> * If mustMatchKingdom is OFF, then the city can produce a new culture, because the culture of the city does not need to match the culture of the kingdom.
> 
> I tried google translate and it came up with "如果启用，叛乱城市的文化必须与其来源王国的文化相匹配。" 
> 
> I don't mean to nitpick, I just want to be sure the translation is right. Let me know if you have any questions.


There is no problem ：） . my translation is partial to the spoken language and the vanilla Chinese translation

**Pull request merged**
